# to use orbs, must use version >= 2.1
version: 2.1
orbs:
  # import Cypress orb by specifying an exact version x.y.z
  # or the latest version 1.x.x using "@1" syntax
  cypress: cypress-io/cypress@1.0.0
workflows:
  build:
    jobs:
      # "cypress" is the name of the imported orb
      # "run" is the name of the job defined in Cypress orb
      - cypress/run:
          yarn: true
          executor: cypress/base-8
          start: yarn setup && yarn start
          wait-on: 'http://localhost:3000'
          command: npx percy exec -- cypress run --record

# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1.0.0
# workflows:
#   build:
#     jobs:
#       - cypress/run:
#           executor: cypress/base-8
#           start: 'npm start' # start server before running tests